### ISSUE TITLE
[Bug] [Back-office] Se permite crear frecuencias cuando el producto es one time payment

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#1]
**Funcionalidad/módulo**
Back-office / Catalog / Products

**Comportamiento actual**
Se permite crear frecuencias cuando el producto es one time payment, lo cual es conceptualmente inconsistente:
![image](https://user-images.githubusercontent.com/12484408/200880325-2a84d7ea-b68b-42ec-af3e-035594cc9c11.png)

![image](https://user-images.githubusercontent.com/12484408/200880553-1d7834f9-bac5-4d68-9d03-e345d8720808.png)

**Resultado esperado**
No se debe poder agregar frecuencias si el producto es "One-time only". El botón "Edit frequency" debería estar deshabilitado con un tooltip indicando que el precio es de pago único por lo cual no se puede agregar frecuencias.

**Notas**
El costo de sign up sólo tiene sentido para suscripciones, no así para pagos únicos, por lo cual, deshabilitar

**Comment by mauromm** [comment]
Resuelto este tema:
<img width="766" alt="image" src="https://user-images.githubusercontent.com/5629108/201380046-b49212a0-c1bb-4b99-ab48-99cb66ae0411.png">
