### ISSUE TITLE
[Tienda] Se permite seleccionar compra única por más que el producto sea de suscripción

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#11]
**Funcionalidad/módulo**
Tienda / Detalle de un producto

**Comportamiento actual**
Se permite seleccionar compra única por más que el producto sea "Subscription only"

<img width="639" alt="image" src="https://user-images.githubusercontent.com/12484408/201781828-f7e13712-631f-42e7-aa71-636a8cd210be.png">

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/12484408/201781676-a4f32e4c-4517-41e9-9c3b-d1309082c007.png">

**Resultado esperado**
Se espera que si el producto es de "Subscription only", no se pueda realizar la compra única.

**Comment by brunojbarros** [comment]
@mauromm 
Se puede agregar el producto como si fuera precio único desde el listado de productos, por más que sea only subscription only:

https://user-images.githubusercontent.com/12484408/203381732-dfc467f5-66f0-4e20-8c5a-aece76fef925.mov

**Comment by mauromm** [comment]
Ya lo estamos revisnado

**Comment by mauromm** [comment]
Ya quedó resuelto esto también.
