### ISSUE TITLE
[Checkout] No se informa al customer que no se permite realizar una compra de productos con distinta frecuencia

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#12]
**Funcionalidad/módulo**
Checkout / Carrito

**Prerequisitos**
Tener configurada la tienda con "Allow mixed cart" = "No".
<img width="538" alt="image" src="https://user-images.githubusercontent.com/12484408/201784663-954ab5ed-be8e-448e-90dd-6c2c41664202.png">

**Pasos**
1. Agregar al carrito un producto.
2. Agregar al carrito un producto con una frecuencia distinta a la del primer producto.
3. Ingresar al carrito
4. Verificar que no se informa al usuario de por qué no puede avanzar con la compra.

**Comportamiento actual**
No se informa al customer que permite realizar una compra de productos con distinta frecuencia (carrito mixto).

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/12484408/201784986-ade40732-aa59-42c7-a035-ef13efb19bac.png">

**Resultado esperado**
Posibles soluciones:
1- Mostrar un mensaje de error al momento de querer agregar un producto con distinta frecuencia y no agregar al carrito el producto.
2- Al ir al carrito, informar que no se puede realizar la compra de productos con distinta frecuencia.

**Comment by mauromm** [comment]
Resuelto:
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/5629108/202528309-1d1f10e4-ccda-4cbf-aa65-1c322b637cb8.png">

También se agregó una customización para que se pueda modificar el texto que muestra en el carrito al pasar esto. Te agrego la ultima version del manual:
[IM-Manual de uso - Módulo Rebill para Magento 2-171122-183602.pdf](https://github.com/improntus/module-rebill/files/10034578/IM-Manual.de.uso.-.Modulo.Rebill.para.Magento.2-171122-183602.pdf)
