### ISSUE TITLE
[Back-office] No se visualiza Customer Document Type ni Customer Attribute for Document

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#13]
**Funcionalidad/módulo**
Back-office / Stores / Configuration

**Comportamiento actual**
No se visualiza Customer Document Type ni Customer Attribute for Document
<img width="817" alt="image" src="https://user-images.githubusercontent.com/12484408/201786805-2632ae55-f1ec-41bc-9f63-d76a703785ae.png">

**Resultado esperado**
Acorde a la documentación, los dropdown Customer Document Type ni Customer Attribute for Document deberían de visualizarse en el apartado de "General".

**Comment by mauromm** [comment]
Habia quedado desactualizado esto en el manual. Te adjunto el correcto, ya que esto no va mas.
[IM-Manual de uso - Módulo Rebill para Magento 2-151122-191916.pdf](https://github.com/improntus/module-rebill/files/10015589/IM-Manual.de.uso.-.Modulo.Rebill.para.Magento.2-151122-191916.pdf)
