### ISSUE TITLE
**CRITICAL** [Dashboard Rebill][Webhooks] Cuando se realiza un pago manual aprobado desde Rebill, no impacta correctamente en la tienda

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#15]
**Funcionalidad/módulo**
Dashboard Rebill
Webhooks

**Pasos**
1. Iniciar sesión en el dashboard de Rebill
2. Ingresar a Suscripciones
3. Presionar en "Detalle" en una suscripción
4. Hacer clic en "Procesar pago"
5. Confirmar el procesamiento.
6. Ingresar a la tienda de Magento como seller
7. Ingresar a Catalog / Products
8. Verificar el stock del producto

**Comportamiento actual**
Cuando se realiza un pago manual aprobado desde Rebill, no se actualiza el stock.

**Resultado esperado**
Se espera que si se realiza un pago manual desde Rebill y el mismo fue aprobado por la pasarela de pagos, se disminuya el stock.

**Comment by mauromm** [comment]
Hola Bruno, cuando se hace esto se tiene que generar un pedido en Magento. Me pasarias el sku y numero de susucripcion con el que te paso?

**Comment by brunojbarros** [comment]
@mauromm 
Suscripción ID: 41d38ded-d267-455b-869d-9ef348cd93ff (https://dashboard.rebill.to/subscriptions/41d38ded-d267-455b-869d-9ef348cd93ff)
Producto: [REB] Producto subscription only - Básico (https://rebillnuevo.improntus.dev/admin/catalog/product/edit/id/2042/set/4/key/dd848a2f73e60edf359014de00322a10f0bd41d819b9c567975c5d29c64aa79f/type/simple/store/0/back/edit/)


Si bien ahora está pausada, podés activarla sin problemas para repetir la prueba.

**Comment by brunojbarros** [comment]
@mauromm 

Acabo de notar que los pagos procesados manualmente en Rebill tampoco se visualizan los pagos en la sección de "Payments" del seller, estimo que debe venir todo por un mismo error, de no ser así avisame y creo un issue aparte.

¿Tenés un estimado de cuándo estaría corregido estos dos puntos _(actualización de stock y que se vea el payment)_?

Tengamos en cuenta que una vez que Rebill les envía el webhook informando el pago, en la tienda debería verse reflejado el pago en menos de 3 segundos.

**Comment by brunojbarros** [comment]
Al hacer procesamiento manual, también está llegando el siguiente email cuando se hace el procesamiento manual:
![image](https://user-images.githubusercontent.com/12484408/204043017-d67507a0-b2bb-4dcd-bc24-d3f5cd5e112a.png)


Por más que el producto exista, esté habilitado y tenga stock.

**Comment by brunojbarros** [comment]
@mauromm 
ya no pude reproducir el error de que al hacer un pago en Rebill no se ve reflejado en Magento, y por lo que me explicaste, el stock no se resta dado que se resta luego de hacer el shipping y es algo manual que debe hacer el seller (Sales / Orders / Detalle de orden / Ship).

¿Podrías comentarme cuál fue el inconveniente en cuanto al pago que no se veía reflejado en Magento?

**Comment by brunojbarros** [comment]
@mauromm 
acabo de detectar que el problema sigue sucediendo cuando se hace el pago manual se hace desde Rebill, y la suscripción tiene más de una cantidad, el pago no llega en magento.

Actualizo la descripción de este bug acorde a lo que está sucediendo ahora.

**Comment by brunojbarros** [comment]
@mauromm 
¿Tenés alguna novedad de este issue?

**Comment by mauromm** [comment]
Bruno, esto seguramente no sea un error, sino un tema de concepto con los qty y los saleable qty que maneja Magento como lo conversamos hace unos dias. 

Tengo este ticket para que lo pruebe nuevamente nuestra QA y aseguremos que sea eso, ya que si se genera el pedido se descuenta el stock correspondiente.

**Comment by brunojbarros** [comment]
@mauromm ¿tenés alguna novedad de esto?

Me quedó claro lo del stock, pero no veo por qué llegan los emails indicando un error: https://github.com/improntus/module-rebill/issues/15#issuecomment-1334538929

**Comment by brunojbarros** [comment]
@mauromm ¿alguna novedad?

Me siguieron llegando algunos emails de error
[Subscription reorder failed.pdf](https://github.com/improntus/module-rebill/files/10282314/Subscription.reorder.failed.pdf)

**Comment by gustavorebill** [comment]
@mauromm Cómo estás?
Tenés alguna novedad sobre este issue?

**Comment by mauromm** [comment]
Va por parte de lo mismo que https://github.com/improntus/module-rebill/issues/61
