### ISSUE TITLE
**CRITICAL** [Dashboard Rebill] Cuando se actualiza la suscripción en Rebill, no se actualiza la misma en la tienda

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#16]
**Funcionalidad/módulo**
Back-office / Catalog / Products

**Pasos**
1. Iniciar sesión en el dashboard de Rebill
2. Ingresar a Suscripciones
3. Presionar en "Detalle" en una suscripción
4. Hacer clic en "Procesar pago"
5. Confirmar el procesamiento.
6. Ingresar a la tienda de Magento como seller
7. Ingresar a Rebill / Subscriptions
8. Verificar la suscripción actualizada
9. Ingresar a la tienda de Magento como customer
10. Ingresar a Suscripciones
11. Verificar la suscripción actualizada

**Comportamiento actual**
Cuando se actualiza la suscripción en Rebill, al cabo de uno/dos minutos, se actualiza la suscripción en la tienda pero no correctamente:
- Como seller, se ve actualizado la siguiente fecha de cobro y el estado. No se puede validar si se actualiza el monto ni la tarjeta, ya que esta información no se muestra en el listado de suscripciones.
- Como customer el único valor que se ve reflejado es el estado, pero no así la siguiente fecha de cobro (next_charge_date), monto ni la tarjeta.

Al parecer, el flujo que se hace al actualizar desde Rebill es el siguiente:
1- Se actualiza en Rebill.
2- Llega a la tienda el webhook de cambio de estado.
3- En la tienda: Se actualiza la suscripción de cara al seller.
4- En la tienda: Se actualiza la suscripción de cara al customer.
5- En la tienda: Se detecta que hay una diferencia entre la suscripción de la tienda con la suscripción que existe en Rebill. La tienda actualiza la suscripción de Rebill con los valores anteriores (monto, tarjeta y siguiente fecha de cobro); al hacerlo, genera que:
a- haya una inconsistencia entre la información que tiene el seller vs la información que tiene el customer y Rebill
b- no respete la actualización que hizo el seller en Rebill.

Rebill:
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/12484408/203214439-9d51e49a-a326-4cb1-9029-27b58a51e992.png">

Magento - Seller - Suscripción en la lista de suscripciones:
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/12484408/203214275-51dc6402-5265-4eb0-9ca1-406316414745.png">

Magento - Customer - Suscripción en la lista de suscripciones:
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/12484408/203214349-73d40e67-85ba-473c-ae1e-38e36b239122.png">

**Resultado esperado**
Se espera que los cambios realizados en Rebill se vean impactados en la tienda.

**Comment by mauromm** [comment]
Cerrada, ya que no pudimos reproducir.
