### ISSUE TITLE
[Back-office][Suscripciones] No se visualiza correctamente la frecuencia

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#17]
**Funcionalidad/módulo**
Back-office / Rebill / Subscriptions

**Comportamiento actual**
Se visualiza solamente la cantidad pero no el tipo de frecuencia, por ejemplo, si es semestral ("6 months") se visualiza solamente "6".

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/12484408/203218346-b1433d6e-fd37-4a96-969f-83e275889395.png">

**Resultado esperado**
Se espera que se visualice cantidad y tipo de frecuencia, por ejemplo, 6 months.

**Comment by mauromm** [comment]
Ya subido esto.
