### ISSUE TITLE
[Back-office][Payments] No se visualiza Payment id ni Card brand

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#18]
**Funcionalidad/módulo**
Back-office / Rebill / Payments

**Comportamiento actual**
No se visualiza Payment id ni Card brand

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/12484408/203218422-0b487e2b-36e1-4a06-b37d-749006c74140.png">

**Resultado esperado**
Se espera que se visusalice Payment id y Card brand.

**Comment by mauromm** [comment]
Ya esta resuelto esto. El "Payment id" no va mas, asi que lo quitamos, al igual que el card brand. 
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/5629108/203644377-42d03549-90b2-48de-af02-695c1aa79d37.png">
