### ISSUE TITLE
[Checkout] Si el seller modifica el SKU del producto, falla la creación de la orden en el checkout

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#19]
**Funcionalidad/módulo**
Checkout

**Pasos**
1. Customer: Hacer checkout de un producto
2. Seller: Modificar el SKU del producto
3. Customer: intentar hacer un checkout del mismo producto

**Comportamiento actual**
No se puede crear el pedido.

https://user-images.githubusercontent.com/12484408/203366257-d3745448-d4c5-4f38-8072-a2e88f6a6c2a.mov

**Resultado esperado**
Se espera que se pueda realizar checkout.

**Comment by mauromm** [comment]
Bruno, no logramos reproducir este problema. De todas formas, es un caso extremadamente raro que se modifique un SKU en una tienda, ya que no son casos habituales.

**Comment by brunojbarros** [comment]
@mauromm 

Si bien es algo raro que cambie el SKU, es un escenario que debe estar contemplado. Igualmente acabo de probar y no pude reproducirlo.

¿Qué hay en los logs para la fecha que se creó el issue? ¿Cómo se puede acceder a los mismos?

Lo que me preocupa es no poderlo reproducir, ya que quizás puede ser otra cosa lo que haya causado el error.

**Comment by brunojbarros** [comment]
Lo reabro para que sigamos analizando lo sucedido.

**Comment by mauromm** [comment]
Te paso los unicos errores que veo en ese día en el log:

[2022-11-22T15:23:51.003718+00:00] rebillLogger.INFO: https://api.rebill.to/v2/item [] []
[2022-11-22T15:23:51.172789+00:00] rebillLogger.INFO: {"name":"[REB] Producto subscription only - B\u00e1sico - UPDATED !!","description":"[REB] Producto subscription only - B\u00e1sico - UPDATED !!"} [] []
[2022-11-22T15:23:51.173212+00:00] rebillLogger.INFO: {"statusCode":500,"timestamp":"Tue, 22 Nov 2022 15:23:51 GMT","path":"/v2/item","message":"Item's name must be shorter than or equal to 50 characters"} [] []

[2022-11-22T15:53:40.731353+00:00] rebillLogger.INFO: https://api.rebill.to/v2/item [] []
[2022-11-22T15:53:40.845290+00:00] rebillLogger.INFO: {"name":"[REB] Producto subscription only - B\u00e1sico - UPDATED !!","description":"[REB] Producto subscription only - B\u00e1sico - UPDATED !!"} [] []
[2022-11-22T15:53:40.845522+00:00] rebillLogger.INFO: {"statusCode":500,"timestamp":"Tue, 22 Nov 2022 15:53:40 GMT","path":"/v2/item","message":"Item's name must be shorter than or equal to 50 characters"} [] []

[2022-11-22T15:57:07.101544+00:00] rebillLogger.INFO: [] [] []
[2022-11-22T15:57:07.101721+00:00] rebillLogger.INFO: [{"name":"Driver license","value":"Driver license"},{"name":"Identity card","value":"Identity card"},{"name":"Social Security card","value":"Social Security card"},{"name":"Passport","value":"Passport"},{"name":"Passport card","value":"Passport card"},{"name":"Green Card","value":"Green Card"},{"name":"Visa","value":"Visa"},{"name":"Other","value":"Other"}] [] []
[2022-11-22T16:18:50.309543+00:00] rebillLogger.INFO: https://api.rebill.to/v2/item [] []
[2022-11-22T16:18:50.435324+00:00] rebillLogger.INFO: {"name":"[REB] Producto subscription only - B\u00e1sico - UPDATED !!","description":"[REB] Producto subscription only - B\u00e1sico"} [] []
[2022-11-22T16:18:50.435611+00:00] rebillLogger.INFO: {"statusCode":500,"timestamp":"Tue, 22 Nov 2022 16:18:50 GMT","path":"/v2/item","message":"Item's name must be shorter than or equal to 50 characters"} [] []

Parece que no tiene algo que ver con el sku sino con el largo del nombre que no le gusta a la api.

**Comment by brunojbarros** [comment]
@mauromm 

Habría que agregar restricciones al front de la tienda entonces:
Cantidad de caracteres máximo:
- Nombre del item: 50
- Descripción del item: 150
- Descripción del precio: 255

Por otro lado, el monto del precio también tiene restricciones, generé el siguiente ticket al respecto: https://github.com/improntus/module-rebill/issues/38

**Comment by mauromm** [comment]
Bruno, no hay chance de agregar esas restricciones en la tienda. No podemos tocar los atributos de producto de una tienda ya que generaríamos un quilombo astronomico con los clientes. 

Lo que podemos hacer, es poner un trim de caracteres en lo que se envía a la API de rebill al momento de crear el item. Llegarán cortados los nombres en algunos casos, pero es el menos danino de los casos.

**Comment by brunojbarros** [comment]
@mauromm 
¿Tienen un estimado de cuántos caracteres suele usar el merchant en sus productos? Para tenerlo en cuenta de nuestro lado para un futuro.

¿Se puede agregar un mensaje _(como el que agregaron cuando se ingresa un email inválido)_ para los casos en los que supere los 50 caracteres? Informándole que en Rebill se limitará a guardar el producto con 50 caracteres.

**Comment by mauromm** [comment]
**Nombre del item**
No te puedo decir un estimado porque es muy muy variable, pensá que a traves de Magento se puede vender lo que sea, en cualquier parte del mundo. El dato que te puedo dar, es que magento valida como máximo a 255 caracteres en el nombre de producto, así que con que se ajuste a este parámetro en Rebill no va a haber mas problema.

**Descripción del item**
Esta parte es la mas complicada, ya que la descripción en los productos de magento puede ser de miles de caracteres. Este atributo es del tipo text en la base y se puede meter lo que sea (hasta html). En este caso no quedaría otra que poner un trim a 150 o que amplien a muchos caracteres.

**Descripción del precio**
Veo que no habria problema para este caso en 255

**Comment by mauromm** [comment]
¿Se puede agregar un mensaje (como el que agregaron cuando se ingresa un email inválido) para los casos en los que supere los 50 caracteres? Informándole que en Rebill se limitará a guardar el producto con 50 caracteres.

En este caso no se puede hacer, ya que implica modificar los validation source de un atributo. En las configuraciones de panel es mucho mas simple porque no se toca este tipo de información, y solo se añaden las validaciones mediante un xml particular a cada modulo.

**Comment by brunojbarros** [comment]
@mauromm 
Vamos a actualizar:
item.name: 255 caracteres.
item.description: 500 caracteres.

Se va a mantener igual price.description 

Todavía no está implementado en producción este cambio, pero se podría ir aplicando estas modificaciones en el plugin.

Con respecto a que no se pueda modificar la validación de un atributo que es por defecto, ¿el mensaje se podrá agregar en algún lado? Por ejemplo, debajo de "You saved the product." agregar un segundo mensaje... Más allá del detalle del cómo, la idea es informarle de forma clara al seller qué se le va a truncar el nombre del producto en Rebill por haber superado el límite.

**Comment by brunojbarros** [comment]
@mauromm 

Me acaba de pasar este error:

![image](https://user-images.githubusercontent.com/12484408/205380574-d0e40acb-16eb-479f-b4d7-8775c9ae00a7.png)

¿Pueden confirmarme si el problema es la longitud de caracteres?

**Comment by mauromm** [comment]
Tenes la hora aproximada a la que te paso?

**Comment by brunojbarros** [comment]
@mauromm 
02/12 17:31hs GMT-3

**Comment by brunojbarros** [comment]
@mauromm 
¿Pudiste ver este tema?

**Comment by mauromm** [comment]
No encontré log de que te pudo haber pasado en ese momento.

**Comment by brunojbarros** [comment]
@mauromm 
¿pudieron restringir acorde a lo indicado en este [comentario](https://github.com/improntus/module-rebill/issues/19#issuecomment-1332793052)?

**Comment by mauromm** [comment]
Bruno, le vamos a poner un trim a 500 caracteres para la descripción. En el día de hoy seguro lo subimos.

**Comment by MauroImp91** [comment]
@brunojbarros 

Después de realizar algunas pruebas con esto vimos que en los response que para el name solo acepta un máximo de 50 caracteres y para la descripción solamente 150 caracteres. 
Por lo tanto por el momento les modificamos para que acepten esos máximos, al momento en que ustedes cambien estos parámetros nos podrán avisar así actualizamos también desde nuestro lado?

**Comment by brunojbarros** [comment]
@MauroImp91 @mauromm 

Ya déjenlo preparado para que limite con [estos valores](https://github.com/improntus/module-rebill/issues/19#issuecomment-1332793052), ya que, en tal caso, fallaría ahora y con el cambio.

Una vez que nosotros deployemos, ya no será necesario que realicen cambio alguno, y quedará de nuestro lado validarlo.

**Comment by brunojbarros** [comment]
@MauroImp91 @mauromm 

Ya está impactado este cambio en producción.

**Comment by MauroImp91** [comment]
@brunojbarros 
Perfecto Bruno, desde nuestros lado ya está configurado para que envié hasta esa cantidad de caracteres que mencionaste en comentarios anteriores.
