### ISSUE TITLE
[Tienda] El carrito se visualiza de manera incorrecta

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#20]
**Funcionalidad/módulo**
Tienda / Carrito

**Comportamiento actual**
Luego de agregar un producto al carrito, cuando se ingresa al detalle de otro producto o bien del mismo pero con otras características (por ejemplo, otra frecuencia), al abrir el carrito ubicado en la parte superior derecha se actualiza con los valores del producto que se está visualizando actualmente.

https://user-images.githubusercontent.com/12484408/203407933-27bf1479-5ecc-470a-a6f7-ec1bdffbad08.mov

**Resultado esperado**
Se debería de visualizar los productos agregados con sus valores correspondientes.

**Comment by mauromm** [comment]
Ya lo estamos revisando

**Comment by mauromm** [comment]
Resuelto:
<img width="681" alt="image" src="https://user-images.githubusercontent.com/5629108/203849064-a25de995-514c-429a-9501-bb18e84b5784.png">
