### ISSUE TITLE
[Back-office] No se puede crear una frecuencia con precio o sign up con valor decimal

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#21]
**Funcionalidad/módulo**
Back-office / Catalog / Products

**Comportamiento actual**
No se puede crear una frecuencia con precio o sign up con valor decimal

https://user-images.githubusercontent.com/12484408/203419367-1c9d45e5-f2c6-47ad-b16e-ffebe0c85f4e.mov

**Resultado esperado**
Se espera que se pueda crear frecuencias indicando precio y/o sign up con valor decimal.

**Comment by mauromm** [comment]
Resuelto:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/5629108/203854020-92bdd31c-b218-4d9a-9712-754f13d17f6b.png">

**Comment by brunojbarros** [comment]
Si bien se puede seleccionar, luego no se puede hacer la compra, queda en un loop o bien tira el error "Hubo un error al crear el pago, intente nuevamente.":


https://user-images.githubusercontent.com/12484408/204018258-a160e4d4-cc19-4aef-91b6-dff7f6ecb92b.mov

**Comment by brunojbarros** [comment]
@mauromm cerré nuevamente este issue, creé el siguiente: https://github.com/improntus/module-rebill/issues/30
