### ISSUE TITLE
**CRITICAL** [Checkout] Se está realizando un pago único por más que se seleccione una suscripción

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#22]
**Funcionalidad/módulo**
Checkout

**Comportamiento actual**
Cuando se selecciona suscribirse a un producto, se agrega al carrito como un producto de único pago, al avanzar con la orden, se genera efectivamente un pago único.

https://user-images.githubusercontent.com/12484408/203428446-20ea5126-9909-4d1a-8797-ea97f77ccc62.mov

**Resultado esperado**
Se debe respetar la frecuencia seleccionada.

**Comment by brunojbarros** [comment]
@mauromm al parecer sucede solamente con aquellas que son "Subscription only", pero no cuando es "One time  and subscription".
Después de corregir este bug, probar de ambas maneras para asegurarse que este mismo error luego no se reproduzca en el escenario de "One time  and subscription".

**Comment by mauromm** [comment]
Ya esta resuelto Bruno, al parecer falto una validación cuando cambiamos esta parte.
