### ISSUE TITLE
[Customer portal] Las suscripciones no están ordenadas

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#23]
**Funcionalidad/módulo**
Customer portal / Suscripciones

**Comportamiento actual**
Las suscripciones no están ordenadas.

![image](https://user-images.githubusercontent.com/12484408/203645069-31768465-4c53-4f4e-92fc-ef086f265fe3.png)

**Resultado esperado**
Se espera que se ordenen por fecha de creación.

**Comment by mauromm** [comment]
Resuelto: ahora se ordena de arriba hacia abajo con los mas nuevos a los viejos, tal como se hace con el listado de pedidos de magento.
