### ISSUE TITLE
[Customer portal][Subscriptions] No se lista las iteraciones restantes

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#25]
**Funcionalidad/módulo**
Back-office / Rebill / Subscriptions

**Comportamiento actual**
No se visualiza la cantidad de suscripciones restantes.

![image](https://user-images.githubusercontent.com/12484408/203649547-9f117cf1-6f41-43b6-9781-ce7a89d4fc26.png)

**Resultado esperado**
Se espera que se visualice la cantidad de iteraciones restantes.

**Comment by mauromm** [comment]
Listo.

**Comment by brunojbarros** [comment]
@mauromm 

Cuando es recurrente, se ve "Iteraciones restantes" = 0, pero en realidad sí hay iteraciones restantes, pero no tienen fin.

Se podría mostrar un "-" para mantener una coherencia con lo que mostramos actualmente en Rebill.

**Comment by mauromm** [comment]
Listo, ya le pusimos un "-".
