### ISSUE TITLE
[Back-office][Subscriptions] No se visualiza correctamente el valor de "Cantidad" de las suscripciones

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#26]
**Funcionalidad/módulo**
Back-office / Rebill / Subscriptions

**Comportamiento actual**
No se visualiza correctamente el valor de "Cantidad" de las suscripciones, sino que siempre se visualiza "1".

![image](https://user-images.githubusercontent.com/12484408/203649438-047547d2-e2f9-487a-b33b-c6a3c140319e.png)

![image](https://user-images.githubusercontent.com/12484408/203649985-9e1d4bac-701f-4ceb-87dc-e5ec1a7eef6d.png)

**Resultado esperado**
Se espera que se visualice la cantidad correspondiente, ver en el caso de ejemplo, que al carrito se agregó 2 y la compra efectuada también fue por 2, pero luego se visualiza Cantidad = 1.

**Comment by mauromm** [comment]
Resuelto esto:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/5629108/203989971-191d2371-e391-4f5e-b188-48e8aac58ac4.png">

Lo vas a ver correctamente a partir de nuevas suscripciones.
