### ISSUE TITLE
[Back-office] El tooltip de Max Recurring Payments se visualiza de manera incorrecta

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#3]
**Funcionalidad/módulo**
Back-office / Catalog / Products

**Comportamiento actual**
En el tooltip de Max Recurring Payments, la palabra "is" pareciera estar solapado con otro elemento.
![image](https://user-images.githubusercontent.com/12484408/200907598-b7700279-0400-4e7e-adb5-2d3f4a1d912f.png)

**Resultado esperado**
Modificar el texto para que sea correcto.

**Comment by mauromm** [comment]
Ya esta resuelto. 
<img width="502" alt="image" src="https://user-images.githubusercontent.com/5629108/201200645-3a7da2d9-3dca-4489-93bd-9530f12ed864.png">
