### ISSUE TITLE
**CRITICAL** [Checkout] No se puede hacer checkout si tiene valor y/o signup cost decimal

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#30]
**Funcionalidad/módulo**
Checkout

**Comportamiento actual**
No se puede hacer checkout si tiene valor y/oy signup cost decimal

https://user-images.githubusercontent.com/12484408/204023443-7d7d7a54-2f00-488f-8aea-e0a57a260cc8.mov

**Resultado esperado**
Se espera que se pueda hacer checkout.

**Comment by mauromm** [comment]
Bruno, lo estamos revisando y nos encontramos con que en el amount esta enviando:

{"amount":"**2.3400000000001**","type":"fixed","repetitions":1,"currency":"ARS","gatewayId":"102f25b7-d0ca-4ddf-aab9-ddad41a211d4","description":"Order #000000057 Additional Costs","enabled":true} 

Con lo cual la api responde:

{"statusCode":400,"timestamp":"Fri, 25 Nov 2022 17:29:41 GMT","path":"/v2/item/22f2e5e7-ce5e-4cb0-91cd-9bc622dff826/price","message":"Amount value should have less than or equals to 5 decimals"}

Por casualidad agregaste ese 00000000001 por alguna prueba? o quizas hay algun otro tema que tenemos que chequear

**Comment by brunojbarros** [comment]
@mauromm 
En una primera instancia envié:
900.987654321 como precio
2.87887766 como signup cost

Luego lo modifiqué a los valores a algo más real, que es lo que tiene ahora:
900.1 y 2.34 respectivamente.

Estimo que si intentan hacer un checkout con este mismo producto "[REB] Producto one time and subscription - Básico" con frecuencia bimestral (es el que tiene dicha config) van a poder reproducir el problema.

En cuanto a la cantidad de decimales, es correcto, no permitimos más de 5 decimales, así que habría que limitar los inputs a dicha cantidad de decimales. Veo que es un comportamiento por defecto en el "Price" general del producto, pero no así dentro de la frecuencia.

**Comment by mauromm** [comment]
Bruno, por favor elimina esas frecuencias y volvé a grabarlas por si quedó algo mal en la base.

**Comment by brunojbarros** [comment]
@mauromm 
Creé de cero un producto (no cloné el existente, sino que es uno totalmente nuevo), le indiqué los mismos valores en el precio y en las frecuencias que tiene el producto "[REB] Producto one time and subscription - Básico", y pude reproducir el error nuevamente.

Igualmente, en caso de que haya quedado guardado algo erróneamente en la base, debería prevenir que dicho escenario suceda.

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/12484408/204366040-8ed32ec5-48fb-4cad-b018-5e561f98f240.png">

**Comment by mauromm** [comment]
Bruno, proba nuevamente por favor. Ya encontramos una manera de resolverlo.
