### ISSUE TITLE
[Checkout] No se respeta el Sort Order indicado por el seller

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#32]
**Funcionalidad/módulo**
Back-office / Catalog / Products

**Comportamiento actual**
No se respeta el Sort Order indicado por el seller, por ejemplo, al indicar sort order = 0 o sort order = 1, se espera que se visualice como primer método de pago, sin embargo se visualiza al final.

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/12484408/204156651-14c709e4-dde2-4c12-b1be-783d4fee59ea.png">

**Resultado esperado**
Se espera que Rebill figure posicionado como método de pago en el orden que indicó el seller en Stores / Configuration (en Settings) / Sales / Payment Methods

**Comment by mauromm** [comment]
Hola Bruno, el sort order en Magento funciona siempre de menor a mayor con los numeros. Por defecto todos vienen con 0, con lo cual si queres que aparezca primero, tenes que poner un numero chico y al resto otro grande. No necesariamente tiene que ser consecutivo. Por ejemplo, podes poner -5 a rebill o alguno negativo y con eso está.

**Comment by brunojbarros** [comment]
Se ingresó un número negativo y se ordenó correctamente:
<img width="1301" alt="image" src="https://user-images.githubusercontent.com/12484408/204284603-04b4a24d-014d-499e-9ae0-3b6d3006a05e.png">
