### ISSUE TITLE
[Back-office][Configuration] Se permite ingresar valores inválidos en Sort Order

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#33]
**Funcionalidad/módulo**
Back-office / Stores / Configuration (en Settings) / Sales / Payment Methods

**Comportamiento actual**
Se permite ingresar valores inválidos en Sort Order.

<img width="759" alt="image" src="https://user-images.githubusercontent.com/12484408/204158714-af790361-ec09-42c7-8519-9cb49f80ebf3.png">

**Resultado esperado**
Se debe permitir ingresar solamente números enteros. No se debe permitir la letra "e".

**Comment by mauromm** [comment]
Resuelto:
<img width="690" alt="image" src="https://user-images.githubusercontent.com/5629108/204574660-41c9a436-5f5e-40c8-8ee9-03da21c66188.png">
