### ISSUE TITLE
[Back-office][Configuration] Se permite ingresar un email inválido

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#34]
**Funcionalidad/módulo**
Back-office / Stores / Configuration (en Settings) / Sales / Payment Methods

**Comportamiento actual**
Se permite ingresar un email inválido en "Email for failed reorder" y en "Api User Email".

<img width="687" alt="image" src="https://user-images.githubusercontent.com/12484408/204160120-e4762d24-3bb5-476c-a359-6b2d4928c365.png">

**Resultado esperado**
Se espera que no se permita ingresar un email inválido en "Email for failed reorder" y en "Api User Email".

**Comment by mauromm** [comment]
Resuelto:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/5629108/204574925-26435197-a27b-4bc1-b1a1-65845ece868f.png">
