### ISSUE TITLE
[Tienda] No se visualiza correcto el logo/texto para identificar si es un producto de suscripción

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#35]
**Funcionalidad/módulo**
Tienda

**Comportamiento actual**
No se visualiza en todos los productos el logo/texto para identificar que es un producto de suscripción, sino que solamente se está visualizando en el primero. Además, al ingresar a los productos, en algunos casos se visualiza el logo y en otro el texto

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/12484408/204181505-4d65d785-aa34-47dd-8c49-9170296f3874.png">

https://user-images.githubusercontent.com/12484408/204181873-0517d359-d80a-431a-9475-54a62700c4b9.mov

**Resultado esperado**
Se espera que se visualice el logo o el texto personalizado según lo configurado por el seller. Dicha configuración debe visualizarse tanto en el listado de productos como también al ver el detalle de los mismos. Además, no debe demorar más de 3 segundos en aplicarse el cambio.

**Comment by brunojbarros** [comment]
@mauromm 
Cambié de texto a logo, pero solamente se visualiza el logo al ingresar al detalle del producto.

https://user-images.githubusercontent.com/12484408/204598231-b212b277-70ac-4e2a-abd8-3f07bdb8e1ae.mov

**Comment by mauromm** [comment]
Bruno, estamos probando cambiar entre el logo y texto en este entorno y nos funciona correctamente. ¿Estas limpiando el cache de magento despues de cada cambio?

**Comment by brunojbarros** [comment]
@mauromm 

No, no estoy limpiando caché de magento ni del navegador. ¿A ustedes les toma inmediatamente el cambio o les demora en aplicar?

**Comment by mauromm** [comment]
Aahh ok, ese es el tema entonces. Cada vez que realices cambios, ya sea en la configuración, productos, categorías, etc, es necesario limpiar la cache de magento para que se reflejen correctamente:

<img width="329" alt="image" src="https://user-images.githubusercontent.com/5629108/205057758-7c684a83-f256-4cb1-a33e-c59bac28c53f.png">

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/5629108/205057894-5f06b653-914b-4f9b-81e5-633b749b64c7.png">

Sin hacer esto, no se reflejan los cambios correctamente, ya que es la manera en que magento eficientiza la carga del sitio al usuario final. No hace falta la caché del navegador.
