### ISSUE TITLE
[Tienda] Se listan productos de "Subscription only" que no tienen configurado frecuencia

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#36]
**Funcionalidad/módulo**
Tienda

**Comportamiento actual**
Se listan productos de "Subscription only" que no tienen configurado frecuencia, por lo cual, el customer debería de poder comprarlos.

Producto sin frecuencia:
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/12484408/204265225-fc656374-87e0-402d-97c4-26bc1728d27c.png">

El producto se lista con los demás productos:
<img width="801" alt="image" src="https://user-images.githubusercontent.com/12484408/204264976-aa7196c6-fecf-4aca-8dd5-ec7d53a8a70a.png">

El producto puede ser agregado al carrito:
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/12484408/204265585-e35e99ff-1d1c-4fe4-b2e0-4b9c589e02b5.png">

**Resultado esperado**
Si el producto es de "Subscription only" y no tiene configurado frecuencia, no debería ser visible para el customer.

**Comment by mauromm** [comment]
Resuelto.
