### ISSUE TITLE
[Tienda] El texto "SignUp Cost" varía si el producto tiene "Max Recurring Payments" o no

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#37]
**Funcionalidad/módulo**
Tienda

**Comportamiento actual**
El texto "SignUp Cost" varía si el producto tiene "Max Recurring Payments" o no; cuando producto tiene "Max Recurring Payments" se visualiza "con una tarifa de", de lo contrario se visualiza "con costo inicial de".

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/12484408/204269955-619c463d-60cf-4583-a82a-85d4e35d2e81.png">

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/12484408/204271236-ee83c1db-96a1-4bc7-a35e-ebfddec14beb.png">

**Resultado esperado**
El texto debería de ser el mismo.

**Comment by mauromm** [comment]
Resuelto, ahora quedó unificado para que diga “con un costo inicial de“.
