### ISSUE TITLE
[Tienda] Se puede agregar productos de "Subscription only" que no tienen configurado frecuencia

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#40]
**Funcionalidad/módulo**
Tienda

**Comportamiento actual**
Similar al https://github.com/improntus/module-rebill/issues/36 .

Si bien los productos "Subscription only" que no tienen configurado frecuencia no se listan en la tienda, si se ingresa a la URL del producto directamente, se permite comprar el mismo.

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/12484408/204783927-87db9c4c-5d48-45f3-a32b-d840062c7ede.png">

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/12484408/204784408-3bb7644e-6696-4efb-b8e2-b22dab8f1c22.png">

Tener en cuenta que esto es un caso border, ya que difícilmente el seller cree un producto de suscripción con frecuencias, un customer ingrese al producto y el seller elimine la frecuencia.

Darle poca prioridad a este issue.

**Resultado esperado**
El customer no debería de poder agregar al carrito productos de "subscription only" que no tienen frecuencia creada.

**Comment by mauromm** [comment]
Bruno, agregamos una validación extra para que no muestre ningún botón de añadir al carrito en caso de que no tenga frecuencias creadas.
