### ISSUE TITLE
[Customer portal] No se visualiza correctamente el monto total de la suscripción

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#41]
**Funcionalidad/módulo**
Customer portal

**Comportamiento actual**
En la columna de "Total", se visualiza el valor unitario del producto, y no el monto total (valor unitario * cantidad).

![image](https://user-images.githubusercontent.com/12484408/205149057-d4d5d987-e3c5-4632-bb07-d2e2de7351b7.png)

**Resultado esperado**
En la columna "Total" se debe mostrar valor unitario * cantidad, o bien mostrar "Valor unitario" (o similar) en dicha columna; idealmente, mostrar ambas columnas.

**Comment by mauromm** [comment]
Resuelto, ahora se multiplica el precio por la cantidad.
