### ISSUE TITLE
[Tienda] La cantidad de items no coincide con la cantidad de productos

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#43]
**Funcionalidad/módulo**
Tienda

**Comportamiento actual**
La cantidad de items no coincide con la cantidad de productos, por ejemplo, hay 8 productos, pero figura "10 items" en la parte superior izquierda.

![image](https://user-images.githubusercontent.com/12484408/205377231-ba108507-ff2b-44da-9633-ceb6a00acc5b.png)

Intenté limpiando caché, pero el problema persiste.

**Resultado esperado**
Se espera que se visualice correctamente la cantidad de items.

**Comment by brunojbarros** [comment]
@mauromm 

Veo que la cantidad de items es 11 pero hay 9 productos. En otras categorías no sucede este mismo inconveniente. ¿Cómo se puede solucionar y evitar que vuelva a suceder?

**Comment by mauromm** [comment]
Ya encontramos a qué se debe esto. Los productos que no tienen frecuencias creadas y son de suscripción no se estan mostrando, pero hay un tema de complejidad con el catálogo. Lo que vamos a hacer, es mostrar los productos igualmente, pero ocultar los botones y selectores para añadir al carrito.

**Comment by mauromm** [comment]
Ya esta resuelto Bruno, ya funciona de la misma manera que si un producto no tuviera frecuencia: se muestra en el catalogo, pero no deja agregarlo como suscripción (en caso de que solo sea una suscripcion):
<img width="631" alt="image" src="https://user-images.githubusercontent.com/5629108/206014871-074c6574-556f-42e2-ac4a-bc565debeef8.png">
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/5629108/206014931-5192f0be-297e-4052-bb40-047ce3125d9c.png">
