### ISSUE TITLE
** CRITICAL ** [Customer portal] Al querer transicionar de estados rápidamente, se comienzan a enviar constantemente requests

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#44]
**Funcionalidad/módulo**
Customer portal

**Comportamiento actual**
Al querer transicionar de estado rápidamente (por ejemplo, pausar la suscripción, y luego activarla, en menos de un minuto), se comienzan a enviar constantemente requests.

**Resultado esperado**
No debe enviarse continuamente requests, sino una única vez.

Una posible solución es restringir que el customer solicite cambios de estados continuamente, por ejemplo, para cambiar el estado nuevamente debe haber transcurrido al menos dos minutos desde el último cambio de estado.

**Comment by brunojbarros** [comment]
@mauromm 
Además de corregir para que no vuelva a suceder esto, es necesario que pausen las requests que están haciendo continuamente.

**Comment by mauromm** [comment]
Bruno, estuve validando con el equipo y podemos poner un if 'status' != 'status' dentro de la funcion updateStatus para que ignore el webhook si lo que viene es igual a lo que hay. Con eso ya no debería pasar el loop. Te aviso cuando este subido.

**Comment by brunojbarros** [comment]
@mauromm 
tengan presente el otro inconveniente que les comentaba:
cuando se hace clic para cambiar de estado (por ejemplo, pausar la suscripción), están enviando dos requests en vez de uno.

**Comment by mauromm** [comment]
Bruno, ya esta resuelto esto. Solo tengo un comentario que me hizo el dev con esto:

> Tanto al pausar como al reactivar, **debería de enviarse como body únicamente el status, dado que es lo que se está queriendo modificar.**

Me dice que al ser un request PUT se deben enviar todos los campos y no deja solamente el status.

**Comment by brunojbarros** [comment]
@mauromm 

¿Cuál endpoint están usando?

El siguiente endpoint https://api.rebill.to/v2/subscriptions/{id} no es necesario enviar todos los campos en el body.

La [documentación](https://docs.rebill.to/reference/clientcontroller_updatecustomersubscription) todavía no se actualizó.

**Comment by brunojbarros** [comment]
@MauroImp91 @mauromm 

Sí, sigue siendo un PUT:

`PUT https://api.rebill.to/v2/subscriptions/{id}`

Para pausar:
```
{
    "status": "PAUSED"
}
```


Para reactivar:
```
{
    "status": "ACTIVE"
}
```

**Comment by brunojbarros** [comment]
Actualicé el ticket acorde a la problemática actual.

**Comment by brunojbarros** [comment]
@mauromm @MauroImp91 

Avancemos con agregar en el header "origin": "magento":
1. Al realizar la compra: `POST /checkout`
2. Al pausar o activar la suscripción desde el customer portal: `PUT /subscriptions/{id}` (en este caso, entiendo que )
3. Al cancelar la suscripción desde el back-office: `PUT /subscriptions/{id}`
4. Al cancelar la suscripción desde el customer portal `DELETE /clients/subscriptions/{subscriptionId}`


¿Puede ser que para cancelar la suscripción estando logueado como seller estén usando el endpoint `DELETE /clients/subscriptions/{subscriptionId}` en vez de `PUT /subscriptions/{id}`?
Tengan en cuenta, que de ser así, están realizando requests innecesarios, ya que estimo que lo que realizan es:
1. Hacer uso de `POST /organization/customer-token` para generar un token
2. Cancelar la suscripción con `DELETE /clients/subscriptions/{subscriptionId}`

Cuando si usaran `PUT /subscriptions/{id}` no necesitarían un paso previo, ya que el token del seller lo tienen cacheado por 24 horas.

**Comment by MauroImp91** [comment]
@brunojbarros , estuvimos revisando las posibilidades que conversamos, y pensamos que lo ideal es que si son cambios de estado que salen desde magento, no se debería de volver a enviar un webhook por un tema de performance, ya que se estarían procesando requests innecesarios en la cola del cron de magento.
Por eso mismo les proponemos que al momento de realizar un cambio de estado, les enviemos hacia la API aparte del parámetro "status" otro parámetro que contenga la información de donde se origina este cambio de estado, para que desde su lado puedan validar si se genera un webhook o no.

**Comment by brunojbarros** [comment]
@MauroImp91 

Justo minutos antes había hecho este comentario: https://github.com/improntus/module-rebill/issues/44#issuecomment-1341534611

Avisame si ves algún inconveniente al respecto, y quedo atento al a pregunta que hago al final.

**Comment by MauroImp91** [comment]
@brunojbarros 

Vamos a trabajar sobre esos cambios que comentas en el header. 
Sobre el tema de cancelar una suscripción que deberíamos de enviar en el body? Entiendo que "status" pero que valor se debe enviar precisamente?

**Comment by brunojbarros** [comment]
@MauroImp91 

Para cancelar usando `PUT /subscriptions/{id}`habría que enviar el siguiente payload:
```
{
"status": "CANCELLED"
}
```

**Comment by mauromm** [comment]
> 1. Hacer

Bruno, ya subimos estos cambios. Esta listo del lado de ustedes el cambio del header?

**Comment by mauromm** [comment]
Bruno, pudieron revisar si esta bien del lado de ustedes? ya subimos todo y lo probamos, pero necesitamos tu confirmación.

**Comment by brunojbarros** [comment]
@mauromm 

El cambio está realizado pero todavía no está subido al ambiente productivo, en cuanto lo hagamos te aviso, tenemos planificado para el día lunes realizar el pasaje a producción de este cambio junto con otros cambios _(ninguno debería de tener impacto en el plugin)_.

**Comment by mauromm** [comment]
Ok perfecto, entonces quedamos para revisarlo nuevamente cuando este subido ese cambio a productivo.

**Comment by mauromm** [comment]
Bruno, pudieron subir este cambio a productivo, asi cerramos este ticket?

**Comment by brunojbarros** [comment]
@mauromm @MauroImp91 

Según conversamos el viernes, no deberíamos hacer cambio alguno de nuestro lado.

**Comment by mauromm** [comment]
Ok perfecto, entonces marco como cerrado este ticket.

**Comment by brunojbarros** [comment]
@MauroImp91 @mauromm 

Para aclarar, ¿aplicaron el cambio que hablamos el viernes pasado?

**Comment by MauroImp91** [comment]
@brunojbarros 
Buenas Bruno, se aplico el cambio de que cuando nos llegue un webhook con un estado nuevo, nosotros actualicemos solamente nuestro lado ese Id de Rebill sin volver a actualizar en su lado.
Haciendo las pruebas vimos que dejo de generar ese loop.
