### ISSUE TITLE
**CRITICAL** [Customer portal] Al actualizar el estado de la suscripción, se envían dos requests en vez de uno

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#46]
**Funcionalidad/módulo**
Customer portal

**Comportamiento actual**
Al actualizar el estado de la suscripción, se envían dos requests en vez de uno.

Por ejemplo, 1670427578992 (Dec 07, 2022 at 12:39:38.992 GMT-3) y 1670427605717 (Dec 07, 2022 at 12:40:05.717 GMT-3) nos llegó el mismo request:
```
{
    "amount": "3000",
    "card": "55f86750-0415-44ef-8ff1-db53a72f2fe9",
    "nextChargeDate": "2023-01-07T14:04:14.000Z",
    "status": "PAUSED"
}
```

**Resultado esperado**
Se debe enviar únicamente un request por cada acción.

**Comment by mauromm** [comment]
Cierro este issue que ya quedo resuelto.
