### ISSUE TITLE
*** THE MOST CRITICAL *** [Checkout] Error al querer finalizar la orden se obtuvo "Hubo un error al crear el pago, intente nuevamente."

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#48]
**Funcionalidad/módulo**
Checkout

**Comportamiento actual**
Error al querer finalizar la orden se obtuvo "Hubo un error al crear el pago, intente nuevamente."

**Caso 1)** Haciendo una única prueba en paralelo:
![test-failed-1](https://user-images.githubusercontent.com/12484408/207181415-8a02028b-444e-4254-a835-dc5cf555cc6e.png)

Esto ocurrió entre las 20:15hs y 20:16hs GMT-3 del día 12/12/2022, pero no es algo que haya ocurrido continuamente, sino que fue algo aislado.

[video.webm](https://user-images.githubusercontent.com/12484408/207181394-46a5bde9-98a6-4485-951c-ff8f8e50ad77.webm)

Otras ocasiones que sucedió lo mismo:
- 13/12/2022 10:45hs GMT-3
- 13/12/2022 12:49hs GMT-3

**Caso 2)** Se intentó realizar treinta checkouts, usando cuatro hilos, seis pruebas fallaron, en todas las pruebas los pasos consistieron en:
1. Crear un nuevo customer
2. Crear un address al customer
3. Ingresar a la URL del producto
4. Agregar al carrito todas las frecuencias que tenga el producto, o bien, en caso de producto "one time", simplemente agregarlo
5. **Aplicar un cupón _(en los casos anteriores NO se aplicó cupón)_**
6. Avanzar en el checkout hasta finalizar la compra
8. Ir al detalle de la orden y validar que se haya creado correctamente
9. Una de las pruebas falló.

Las seis pruebas fallaron por diferentes motivos:

- 1 por "A server error stopped your order from being placed." (ver #53)
- 3 por "Hubo un error al crear el pago, intente nuevamente." (origen de este ticket)
- 2 por regresar a la primera pantalla de checkout (ver #55)

18/12/2022 17:01:38 (GMT-3)
62d42f58-2535-468f-8136-163de68115f2@mailsac.com / Password123!

[48677a74608f0c47986c85ed74972cd130c8b4f2.webm](https://user-images.githubusercontent.com/12484408/208321970-05367d22-7b47-4115-8121-18eddb33a437.webm)

18/12/2022 17:04:42 (GMT-3)
ad73377f-074c-4bfe-babd-1a071d6fa8a5@mailsac.com@mailsac.com / Password123!

[e9d0efde96fa0273c02345124559d1cc20cee5a6.webm](https://user-images.githubusercontent.com/12484408/208322006-685dba4e-305e-4c8b-b6c0-c987dfdf5ed1.webm)

18/12/2022 17:07:24 (GMT-3)
a9eec67f-a3cb-4ca8-868c-8fd6172e29ab@mailsac.com@mailsac.com / Password123!

[0d45c37433bc5c71039550e99ccf37b9d69172f2.webm](https://user-images.githubusercontent.com/12484408/208322073-ccb381fd-3b08-4943-a295-af873370d723.webm)

_En ambos casos, todas las fechas son aproximadas, con +/- un minuto de diferencia._

**Resultado esperado**
Se espera que se finalice la orden avanzando a la pantalla posterior.

**Comment by brunojbarros** [comment]
@mauromm ¿alguna novedad sobre esto?

**Comment by mauromm** [comment]
Bruno, veo que los errores que te pasaron estos días viene por tema de decimales y conversión de monedas:

[2022-12-18T03:14:18.167024+00:00] rebillLogger.INFO: {"amount":"1.1216666666667","type":"fixed","repetitions":null,"currency":"EUR","gatewayId":"102f25b7-d0ca-4ddf-aab9-ddad41a211d4","description":"[REB][AUT] Subs only - Without base price","enabled":true,"frequency":{"type":"months","quantity":1}} [] []
[2022-12-18T03:14:18.167314+00:00] rebillLogger.INFO: {"statusCode":400,"timestamp":"Sun, 18 Dec 2022 03:14:18 GMT","path":"/v2/item/b07c1460-ed88-4a24-8eff-06fb25e7b393/price","message":"Amount value should have less than or equals to 5 decimals"} [] []


[2022-12-18T20:03:07.860769+00:00] rebillLogger.INFO: {"amount":"1,090.98000","type":"fixed","repetitions":1,"currency":"EUR","gatewayId":"102f25b7-d0ca-4ddf-aab9-ddad41a211d4","description":"Order #000000543 Additional Costs","enabled":true} [] []
[2022-12-18T20:03:07.860973+00:00] rebillLogger.INFO: {"statusCode":400,"timestamp":"Sun, 18 Dec 2022 20:03:07 GMT","path":"/v2/item/32166026-9583-4d23-ac00-cdc6c14ed6c0/price","message":"Bad Request Exception: amount must be a number string. "} [] []

**Comment by brunojbarros** [comment]
@mauromm 

Probé haciendo un checkout con un precio recurrente NO existente en Rebill, aplicando un cupón con más de dos decimales:

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/12484408/208900489-5f4f1b07-fd45-4dbf-8bdc-359f135e55d5.png">

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/12484408/208900389-f7cd9a64-77b1-441d-b386-06d94df4462a.png">

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/12484408/208901190-13fb2d42-14be-441c-b4fd-cc4ba229aeb9.png">

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/12484408/208902929-5564a60d-1043-4d50-8a40-b8964415b956.png">


Noto que en caso de aplicar un cupón con más de dos decimales:
- En Magento, siempre redondea a dos decimales.
- Es raro ver un cupón de "0,00".
- En Rebill se creó el precio, el pago y la suscripción se realizó con dos decimales, no con cinco


Si bien Magento permite crear productos con más de dos decimales, el plugin permite crear frecuencias de más de dos decimales, y Rebill permite hasta cinco decimales, me surgen algunas cuestiones:
1. ¿En qué situaciones Magento envía solamente dos decimales y en cuáles intenta enviar todos los decimales?
2. Hay que hacer que haya una consistencia entre la información que se visualiza y manipula en ambos lados (Magento y Rebill), no debería de darse por ejemplo, que en Magento se muestre $1.000,12 y en Rebill $1.000,12345
3. El primer mensaje es un error que devuelve Rebill, acorde a lo comentado en el ticket #38 , por lo cual, si está causando problemas al hacer el checkout debería de encararse. Por otro lado, por lo que veo en el segundo mensaje están enviando decimales innecesariamente, tengan cuidado con esto; están queriendo enviar _mil noventa con noventa y ocho centavos_ (en nuestro formato, sería $1.090, 98), pero sin embargo, para la parte decimal, están enviando más decimales que los necesarios, dado que en la parte decimal los ceros a la derecha se pueden omitir. Si intentaran crear un precio de "1.00000" se crearía correctamente, si lo intentaran crear con " 1.000000" (seis decimales) obtendrían el error "Amount value should have less than or equals to 5 decimals" siendo que pudo haberse prevenido.
4. El segundo mensaje se corresponde a que Magento no está enviando correctamente el monto: "1,090.98000", cuando debería de ser: "1090.98000" (tienen que omitir la coma que la están usando como separador de miles)

**Comment by brunojbarros** [comment]
@mauromm @MauroImp91 

Dejo otro ejemplo, en este caso donde solamente está el precio de los productos, frecuencias y sign up cost:

![image](https://user-images.githubusercontent.com/12484408/209017748-659c4f86-223e-425d-a569-b9fec3300a8f.png)


bc33e5fb-d942-445a-af97-5effc49b5cd9@mailsac.com / Password123!

Fecha aproximada en la que ocurrió el error: 21/12/2022 19:44:53 (GMT-3). Van a notar que varios errores cercano a esta hora. Asumo que falló por el segundo error: "amount must be a number string.", dado que no se aplicó ningún descuento ni cupón ni impuesto.

**Comment by brunojbarros** [comment]
@mauromm @mauromm 

¿Cuándo estiman tener esto resuelto?

**Comment by MauroImp91** [comment]
@brunojbarros 

Podrás volver a intentar? Ahí subimos unos cambios que con el ultimo ejemplo que compartiste ya no esta ocurriendo este error.
Avísame cualquier cosa.

**Comment by brunojbarros** [comment]
@MauroImp91 buen día, ¿tienen alguna novedad por este bug?

**Comment by MauroImp91** [comment]
@brunojbarros 

Buenos días Bruno, todavía seguimos trabajando sobre esta issue. Tan pronto tengamos novedades te lo estaremos informando por este medio.

**Comment by MauroImp91** [comment]
@brunojbarros 

Buenos días Bruno, queria informarte que ya subimos los cambios para poder solucionar este problema.
Cuando puedas volve a realizar las pruebas necesarias y cualquier consulta que se presente me avisas!

**Comment by brunojbarros** [comment]
@MauroImp91 

Sigue pasando, dejo algunos casos:
27/12/2022 10:10:46 GMT-3
5d46026f-133b-476f-af9e-a524814d3ae2@mailsac.com
[2a10cfa87fd0317d4ddc228f4fa4255d8912f6fe.webm](https://user-images.githubusercontent.com/12484408/209677366-9cf18b65-692c-4afb-8b34-0f9ba665b0c8.webm)


27/12/2022 10:12:14 GMT-3
21bc5234-1cc9-46ff-a59e-e0839b005050@mailsac.com
[f5ee198cb7c00b20226363810b037ecc258f8d34.webm](https://user-images.githubusercontent.com/12484408/209677473-c528e745-e924-4470-aa80-78581cb4bb8e.webm)


27/12/2022 10:15:47 GMT-3
fdfb48fe-ca9d-49b1-b7b0-9b04d854b476@mailsac.com
[a89d18d6f857bc75a0f2eae52c1a89255678ed2a.webm](https://user-images.githubusercontent.com/12484408/209677556-ca0c351e-57ba-43e9-beed-6b234181b631.webm)


27/12/2022 10:18:27 GMT-3
0a4645df-a3c3-4196-be23-f94b947b970a@mailsac.com
[b6a15a0622a6873af1af37577f0fdad163a13b20.webm](https://user-images.githubusercontent.com/12484408/209677630-ae0d4fa8-5d9d-441a-9e34-2f3647544a08.webm)

**Comment by MauroImp91** [comment]
@brunojbarros 

Gracias por los comentarios, estuvimos revisando esos casos y vemos que el dato por el que fallaba ("amount") es el correcto para esas ordenes.
![image](https://user-images.githubusercontent.com/113549454/209697383-ad69d737-b2b5-4e9c-860c-487f5ab54f10.png)

![image](https://user-images.githubusercontent.com/113549454/209697420-aab5b095-89c5-4903-b6fd-210e09d69423.png)

![image](https://user-images.githubusercontent.com/113549454/209697439-5d83f4ba-1d7d-4139-899d-6411d1426dbb.png)

De todas formas revisando los logs, encontramos dentro de las pruebas que realizaste algunas ordenes que fallaban y gracias a eso pudimos encontrar donde podría generar el error para esos casos.
Te pido una vez mas si puedes volver a realizar las pruebas.
Cualquier novedad estamos atentos.

**Comment by gustavorebill** [comment]
@MauroImp91 
Los errores se continuan reproduciendo 

Subs only - Without base price | Qty: +1 | Shipping: free | Apply tax: true | Coupon: Without coupon

Dec 27 2022 17:53:18 GMT-0300
23a2cbe2-cd8c-47ef-9385-507b7da77223@mailsac.com
[1cde169c1e7fd0ecea73d2941385b3f49971c43f.webm](https://user-images.githubusercontent.com/109085275/209723520-1ec56460-0504-43b2-a496-a05c260159e8.webm)


Prod one time only | Qty: 1 | Shipping: free | Apply tax: true | Coupon: Fixed amount discount for whole cart
Dec 27 2022 17:58:39 GMT-0300
[c6e0ab8b17e0503e0b12d47863f3510f3f30ffb7.webm](https://user-images.githubusercontent.com/109085275/209724429-a6d84c4a-5590-4a00-b7d3-0cde58be222d.webm)


Subs only - Without base price | Qty: +1 | Shipping: flat rate | Apply tax: false | Coupon: Fixed amount discount for whole cart
Dec 27 2022 18:04:36 GMT-0300 
33ca6639-2850-454a-8dda-3d81d6563800@mailsac.com will be created.
[72b9352371cb3004712a804f63a19c7846431e98.webm](https://user-images.githubusercontent.com/109085275/209726290-d973ac77-d44e-4c9e-b934-2500154c12c8.webm)

**Comment by brunojbarros** [comment]
@MauroImp91

Sigue pasando, dejo algunos casos:
Dec 27 2022 20:11:46 GMT-0300
b45158e0-2881-45fb-98d3-23f56244eab2@mailsac.com

[e8788f8cb6169c66ec02dd65f8695a2bd5935cb0.webm](https://user-images.githubusercontent.com/12484408/209809631-889f5784-5f4d-4050-bcd4-f64a02fdb9a9.webm)



Dec 27 2022 20:15:05 GMT-0300
b2c9a03a-2873-4aca-a2b1-674374f2319e@mailsac.com

[4ede23a58e73d55cbb23d6ca15becd83413b882f.webm](https://user-images.githubusercontent.com/12484408/209809848-046d36ae-9d5d-462b-b7b9-e8e81c98823e.webm)



Dec 27 2022 20:14:29 GMT-0300
abf290d6-9db8-4963-b6be-a4369efbb8ce@mailsac.com

[838cc110e66378d998455047bc5ecd28d34744b3.webm](https://user-images.githubusercontent.com/12484408/209809947-d84f641d-db8b-4e9e-9c37-9ea1bff3cdc0.webm)



Dec 27 2022 20:21:03 GMT-0300
99c0bfb5-ed77-48a1-b9ef-b6973be59a47@mailsac.com

[a69331006d72fb72057509ce5731a128f6225d8f.webm](https://user-images.githubusercontent.com/12484408/209810103-390b2a96-72bf-487d-ace7-698c5395cffa.webm)

**Comment by MauroImp91** [comment]
Muchas gracias @brunojbarros.

Por lo que vivos había costos adicionales que generaban números con notación científica, eran muy pocos los casos pero generaban ese error. Ahí subimos un fix para que esto quede solucionado.
Quedo atento ante cualquier novedad.

**Comment by gustavorebill** [comment]
No se puede reproducir el error. Se procede con el cierre del ticket.
