### ISSUE TITLE
[Customer Portal][Login] Al querer iniciar sesión se obtuvo Invalid Form Key. Please refresh the page.

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#49]
**Funcionalidad/módulo**
Customer Portal / Login

**Comportamiento actual**
Al querer iniciar sesión se obtuvo Invalid Form Key. Please refresh the page.

![Invalid Form Key](https://user-images.githubusercontent.com/12484408/207181857-18225e4d-e96c-4bd0-a5c6-dafe50cf6f7a.png)

Esto no es algo que suceda siempre y estimo que no tiene relación con el plugin, pero se debe corregir dado que a veces fallan las pruebas automatizadas por este motivo.

Algunos de estos casos ocurrió aproximadamente:
- 10/12/2022 18:54hs GMT-3.
- 12/12/2022 21:01hs GMT-3.
- 12/12/2022 21:04hs GMT-3.

**Resultado esperado**
Se espera poder iniciar sesión.

**Comment by mauromm** [comment]
Hola Bruno, esto es un tema de cookies. Si te pasa, elimina las cookies y volve a cargar la pagina. Con eso se te resuelve el tema.

**Comment by brunojbarros** [comment]
@mauromm @MauroImp91 

Noto que esto pasa incluso cuando se trata de un sign up, dejo algunos ejemplos:
27/12/2022 20:13:02 GMT-0300
[27f59eaddc9e386cf645670d8dbd96f5cd641fa4.webm](https://user-images.githubusercontent.com/12484408/209741187-da334760-214e-4490-92d8-b124f7078a36.webm)

27/12/2022 20:18:12 GMT-0300
[765ef5d2fbc315d93bf18d451400a36b95db5e81.webm](https://user-images.githubusercontent.com/12484408/209741192-1d35d4ec-e7b6-4a88-bf4f-c4dd8cfa3da1.webm)

27/12/2022 20:17:12 GMT-0300
[870e5d502dab25a7cb0bb3427450ffbf4ca34cb8.webm](https://user-images.githubusercontent.com/12484408/209741196-56e88fa1-028a-4159-a4fb-5cf74d8a60f1.webm)


CC: @gustavorebill

**Comment by facundo-improntus** [comment]
Hola Bruno, no hay ningun proceso en el plugin que afecte o pueda afectar al login o signup de magento.

Esto puede pasar por varios motivos cuando abris la pagina de signup o login:

1 - Al hacer un deploy en la plataforma antes de enviar el formulario
2 - Si se espera mucho tiempo para hacer submit del formulario
3 - Al borrar las cookies antes de enviar el formulario

Cierro este Issue ya que no tiene nada que ver con el comportamiento del plugin.
