### ISSUE TITLE
** CRITICAL ** [Checkout] No se está agrupando correctamente los precios al enviar el payload al hacer POST /checkout

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#51]
**Funcionalidad/módulo**
Checkout

**Comportamiento actual**
No se está agrupando correctamente los precios al enviar el payload al hacer POST /checkout, por ejemplo, al querer hacer checkout del siguiente producto: https://rebillnuevo.improntus.dev/qweewq.html eligiendo ambas frecuencias, el payload que se envía es el siguiente:

![image](https://user-images.githubusercontent.com/12484408/207722489-de6a64e8-743c-4e2f-acf2-32a6695e47be.png)

Por lo cual, desde Rebill indicamos un error y luego se muestra lo siguiente:

![image](https://user-images.githubusercontent.com/12484408/207721887-dbc5fe79-50c7-4bd3-8384-532d79bd60fb.png)

**Resultado esperado**
Los precios se deben agrupar, sumando su valor en cantidad, es decir, en vez de enviar:
```
    "prices": [
        {
            "id": "99218b66-335f-474b-ad57-365ecffe862c",
            "quantity": 1
        },
        {
            "id": "99218b66-335f-474b-ad57-365ecffe862c",
            "quantity": 1
        },
        {
            "id": "bf81d15a-5ba4-4755-9e67-fcb109c311d5",
            "quantity": 1
        }
    ]
```

Debería de enviarse:
```
    "prices": [
        {
            "id": "99218b66-335f-474b-ad57-365ecffe862c",
            "quantity": 2
        },
        {
            "id": "bf81d15a-5ba4-4755-9e67-fcb109c311d5",
            "quantity": 1
        }
    ]
```

**Comment by brunojbarros** [comment]
@mauromm ¿alguna novedad sobre este issue?

**Comment by mauromm** [comment]
Bruno, ya esta subido este fix.
