### ISSUE TITLE
*** CRITICAL *** [Checkout] Al intentar finalizar pedido se visualiza: A server error stopped your order from being placed. Please try to place your order again.

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#53]
**Funcionalidad/módulo**
Checkout 

**Comportamiento actual**
Al intentar finalizar pedido se visualiza: A server error stopped your order from being placed. Please try to place your order again.

**Caso 1)** Contexto:
Se intentó realizar 10 checkouts, usando ocho hilos en paralelo, en todos los casos, los pasos consistieron en:
1. Crear un nuevo customer
2. Crear un address al customer
3. Ingresar a la URL del producto
4. Agregar al carrito todas las frecuencias que tenga el producto, o bien, en caso de producto "one time", simplemente agregarlo
5. Avanzar en el checkout hasta finalizar la compra
6. Ir al detalle de la orden y validar que se haya creado correctamente

Tres de las pruebas fallaron.

Los tres tests fallaron a las 17/12/2022 14:59:23 (GMT-3) aproximadamente: la prueba comenzó _Sat Dec 17 2022 14:58:43 GMT-0300_ y fallaron las tres en el minuto 1:40.
![image](https://user-images.githubusercontent.com/12484408/208255764-928c5329-e4c9-4c29-930b-d301ab136b22.png)

[1056a7b3b31468d6216b15eb31733aceae4a4407.webm](https://user-images.githubusercontent.com/12484408/208255869-0b0d29ef-f1bd-4ae8-bf5b-8f60587cc39f.webm)

Dejo los otros dos vídeos de los tests que fallaron, que si bien no se llega a ver el error, asumo que es por el mismo inconveniente:

[651e201f6dcebbb61f95678474aa58814b92b226.webm](https://user-images.githubusercontent.com/12484408/208256530-58d1f089-1b20-4a69-a03d-16310fc03fcf.webm)

[f3e0e1c4043be55aa6ea6dda797348a964e73adb.webm](https://user-images.githubusercontent.com/12484408/208256537-e89d03a6-db7f-4940-acb9-5c6f545df873.webm)

**Caso 2)** Se intentó realizar treinta checkouts, usando cuatro hilos, seis pruebas fallaron, en todas las pruebas los pasos consistieron en:
1. Crear un nuevo customer
2. Crear un address al customer
3. Ingresar a la URL del producto
4. Agregar al carrito todas las frecuencias que tenga el producto, o bien, en caso de producto "one time", simplemente agregarlo
5. **Aplicar un cupón _(en los casos anteriores NO se aplicó cupón)_**
6. Avanzar en el checkout hasta finalizar la compra
8. Ir al detalle de la orden y validar que se haya creado correctamente
9. Una de las pruebas falló.

Las seis pruebas fallaron por diferentes motivos:

- 1 por "A server error stopped your order from being placed." (origen de este ticket)
- 3 por "Hubo un error al crear el pago, intente nuevamente." (ver #48)
- 2 por regresar a la primera pantalla de checkout (ver #55)

18/12/2022 17:00:14 (GMT-3)
b67e9c58-040c-4727-8ba4-9c68e5425805@mailsac.com / Password123!

[d878d9024481f689b728c01156772d4a6c84d124.webm](https://user-images.githubusercontent.com/12484408/208321445-5e48efbc-794b-487f-ad65-86fe5ec4d3b3.webm)

**Resultado esperado**
Se espera que se pueda finalizar la orden y poder realizar el pago.

Por otro lado, debería de poder soportar muchísima más carga. Por favor, dejar información del servidor (por ejemplo, RAM, cuántos usuarios había en todas las tiendas que usan el mismo servidor, etc) en el momento que se dio este error y cualquier otra información que sea relevante.

Si bien entendemos que esto puede ser una cuestión de hardware, es necesario saber cuáles son los requisitos mínimos que tiene que tener el servidor para soportar distintos niveles de concurrencia: 10.000, 50.000, 100.000, 1.000.000, 10.000.000, N, esto debe estar documentado en el manual de usuario.

**Comment by mauromm** [comment]
Bruno, estos temas me parece mejor que lo veamos en una meet asi explico el por qué de estas cuestiones.

**Comment by gustavorebill** [comment]
@mauromm Buenos Días! Cómo estás?
 Bruno se encuentra de vacaciones. Podemos juntarnos para ver este tema? Que disponibilidad tenes? 

Gustavo

**Comment by gustavorebill** [comment]
@mauromm Buenos días!
Podemos juntarnos para ver este tema?

Gustavo

**Comment by mauromm** [comment]
Pasa por un tema de limite de mails que stopea la ejecucion.

**Comment by brunojbarros** [comment]
Para solventar el inconveniente del email, se configuró que todos los emails se envíen a: [https://mail.rebill.improntus.dev/](https://mail.rebill.improntus.dev/)
