### ISSUE TITLE
*** CRITICAL *** [Checkout] Al querer finalizar la orden, regresa a la primera pantalla de checkout

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#55]
**Funcionalidad/módulo**
Checkout / Finalizar orden

**Comportamiento actual**
Al querer finalizar la orden, regresa a la primera pantalla de checkout. Al iniciar sesión con el customer, el carrito sigue con todos los productos seleccionados.

Esto sucede tanto ejecutando pruebas en paralelo, como ejecutando una única prueba:
**Ejemplo ejecutando una única prueba en paralelo**:
[3e03b7570d6b580d0dd009f37208dbd218e1b915.webm](https://user-images.githubusercontent.com/12484408/207382100-bf4e3f16-49cf-468a-a640-641391533f28.webm)

Horario en el que sucedió:
- 13/12/2022 12:55hs GMT-3

**Ejemplos ejecutando varias pruebas en paralelo**:
**Caso 1)** Se intentó realizar diez checkouts, usando cuatro hilos en paralelo, una prueba falló, todas las pruebas los pasos consistieron en:
1. Crear un nuevo customer
2. Crear un address al customer
3. Ingresar a la URL del producto
4. Agregar al carrito todas las frecuencias que tenga el producto, o bien, en caso de producto "one time", simplemente agregarlo
5. Avanzar en el checkout hasta finalizar la compra
6. Ir al detalle de la orden y validar que se haya creado correctamente
7. Una de las pruebas falló.

Customer: 45cc4c91-cf11-4c59-9f63-2e4349c9f7d9@mailsac.com
Contraseña: Password123!

[3bd63f710fe16500447f528ab69297f8ec50d6ae.webm](https://user-images.githubusercontent.com/12484408/208279277-29a39239-d848-4ade-b9a0-c79d35836682.webm)

La prueba falló 17/12/2022 21:58:02 (GMT-3) aproximadamente: la prueba comenzó Sat Dec 17 2022 23:56:13 GMT-0300 y en el minuto 1:49 se redireccionó a la primera pantalla del checkout.

**Caso 2)** Se intentó realizar diez checkouts, usando cuatro hilos, siete pruebas fallaron, en todas pruebas los pasos consistieron en:
1. Crear un nuevo customer
2. Crear un address al customer
3. Ingresar a la URL del producto
4. Agregar al carrito todas las frecuencias que tenga el producto, o bien, en caso de producto "one time", simplemente agregarlo
5. Avanzar en el checkout hasta finalizar la compra
6. Ir al detalle de la orden y validar que se haya creado correctamente
7. Una de las pruebas falló.

Las pruebas mismas fallaron aproximadamente:
18/12/2022 00:21:45 (GMT-3)
0e607da9-2c67-4fba-9ba3-befa68dec8fb@mailsac.com / Password123!

[a2c136eb892841114693184a7f40bdf6f9c6c020.webm](https://user-images.githubusercontent.com/12484408/208303159-a033a57b-69b5-4896-a899-1f33ae1bfc88.webm)

18/12/2022 00:21:45 (GMT-3)
79959a02-0f26-4d83-be0c-36007d4792f4@mailsac.com / Password123!

[7ec20b01b688a95b5fbb9a171b21a30803d6cad4.webm](https://user-images.githubusercontent.com/12484408/208303046-13c8fde7-8de6-4151-9c23-ef24b21f14ce.webm)

18/12/2022 00:22:38 (GMT-3)
dd4f1786-3f1c-4c23-b38c-ccd1e94e74d7@mailsac.com / Password123!

[e95e470477c89ddda38c36452a170cd2af5703bf.webm](https://user-images.githubusercontent.com/12484408/208303206-01b3d457-45c5-419f-ad0b-4581152c3970.webm)

18/12/2022 00:24:02 (GMT-3)
cce47c9c-7d91-4144-8399-e7b84f8f67eb@mailsac.com / Password123!

[8d2cbe1462630c9d6c1a5c36248eccd0184f031e.webm](https://user-images.githubusercontent.com/12484408/208303070-9e29f251-215b-4728-8aee-1449c476bc68.webm)

18/12/2022 00:24:14 (GMT-3)
38578b0c-b188-4657-b4d5-bf25037d508f@mailsac.com / Password123!

[906c39b32b4bfa70cde30f5edc1e1c50ee0eef95.webm](https://user-images.githubusercontent.com/12484408/208303095-fb7418d0-4aa5-4557-93ea-0e87bdf99afb.webm)

18/12/2022 00:24:28 (GMT-3)
a7e9784e-36ca-4c47-bde3-ba4b616d1745@mailsac.com / Password123!

[4eb25aae51d0676d557d9736fbed36c30d21595d.webm](https://user-images.githubusercontent.com/12484408/208302981-0c999098-a469-46bf-89e5-96622ea67cea.webm)

18/12/2022 00:25:20 (GMT-3)
06b7c969-d91c-4b84-aceb-91e49f5b2c93@mailsac.com / Password123!

[dec9170fd6e59ade7547ae489852f22cf923537d.webm](https://user-images.githubusercontent.com/12484408/208303187-6cdda2f7-35b9-432c-b7ae-64a08f311334.webm)

**Caso 3)** Se intentó realizar treinta checkouts, usando cuatro hilos, seis pruebas fallaron, en todas las pruebas los pasos consistieron en:
1. Crear un nuevo customer
2. Crear un address al customer
3. Ingresar a la URL del producto
4. Agregar al carrito todas las frecuencias que tenga el producto, o bien, en caso de producto "one time", simplemente agregarlo
5. **Aplicar un cupón _(en los casos anteriores NO se aplicó cupón)_**
6. Avanzar en el checkout hasta finalizar la compra
8. Ir al detalle de la orden y validar que se haya creado correctamente
9. Una de las pruebas falló.

Las seis pruebas fallaron por diferentes motivos:

- 1 por "A server error stopped your order from being placed." (ver #53)
- 3 por "Hubo un error al crear el pago, intente nuevamente." (ver #48)
- 2 por regresar a la primera pantalla de checkout (origen de este ticket)

18/12/2022 17:03:01 (GMT-3) 
f50128a1-2998-4151-ad9d-027ebe2300e6@mailsac.com / Password123!

[afb42aa4ab2062c7062215fc250d0ff3143961ab.webm](https://user-images.githubusercontent.com/12484408/208321135-cc3cfd78-25f0-493c-9061-659af4aef4f9.webm)

18/12/2022 17:05:26 (GMT-3) 
1346fa59-b37a-42fa-bc7d-71adb7898412@mailsac.com / Password123!

[3adce5288e5f4698e6e977e68a0490580563f6fd.webm](https://user-images.githubusercontent.com/12484408/208321201-6985ce51-b7c4-4f17-8981-87d02c3ff167.webm)

**Resultado esperado**
Se espera poder finalizar la orden.

**Comment by mauromm** [comment]
Esto paso por lo que comenté aca: https://github.com/improntus/module-rebill/issues/48#issuecomment-1359953540

**Comment by brunojbarros** [comment]
@mauromm 
respondido el 48: https://github.com/improntus/module-rebill/issues/48#issuecomment-1361306596

Si te parece, una vez solucionado el 48 le damos cierre a este también, o bien tomamos este como duplicado dado que el origen del problema es el mismo.

**Comment by brunojbarros** [comment]
Se solucionó el #48 ; y este issue tampoco volvió a suceder, por lo cual, se cierra el mismo.
