### ISSUE TITLE
*** CRITICAL *** [Checkout] Al intentar finalizar pedido se visualiza: Internal Error. Details are available in Magento log file. Report ID: webapi-63ae0e662d9d5

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#57]
**Funcionalidad/módulo**
Checkout

**Comportamiento actual**
Al intentar finalizar pedido se visualiza: Internal Error. Details are available in Magento log file. Report ID: webapi-63ae0e662d9d5

[dd536dd49fabf95ebb0cfda7c2251f85c54a7cae.webm](https://user-images.githubusercontent.com/12484408/210022658-4a90540b-7c5d-4827-9f40-f2de4716ceb7.webm)

Thu Dec 29 2022 19:02:08 GMT-0300
1afb06e2-81a7-45be-971e-a3621ad1c837@mailsac.com

**Resultado esperado**
Se espera poder finalizar la orden y poder avanzar con el checkout.

**Comment by mauromm** [comment]
Next Exception: Report ID: webapi-63ae0e662d9d5; Message: SQLSTATE[HY000] [2002] Connection refused in /var/www/rebillnuevo/vendor/magento/framework/Webapi/ErrorProcessor.php:208
Stack trace:
#0 /var/www/rebillnuevo/vendor/magento/framework/Webapi/ErrorProcessor.php(153): Magento\Framework\Webapi\ErrorProcessor->_critical()
#1 /var/www/rebillnuevo/vendor/magento/module-webapi/Controller/Rest.php(197): Magento\Framework\Webapi\ErrorProcessor->maskException()
#2 /var/www/rebillnuevo/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch()
#3 /var/www/rebillnuevo/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent()
#4 /var/www/rebillnuevo/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
#5 /var/www/rebillnuevo/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins()
#6 /var/www/rebillnuevo/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch()
#7 /var/www/rebillnuevo/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#8 /var/www/rebillnuevo/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#9 /var/www/rebillnuevo/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
