### ISSUE TITLE
[Checkout] No se visualizó el número de orden al hacer checkout

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#58]
**Funcionalidad/módulo**
Checkout

**Comportamiento actual**
No se visualizó el número de orden al hacer checkout

Thu Dec 29 2022 19:02:07 GMT-0300
b452bae0-dbc8-4b74-af6b-dcddff107e72@mailsac.com

![image](https://user-images.githubusercontent.com/12484408/210026912-201f0289-e7f2-44ec-85e8-2c310c574c43.png)

[9ad01e04e9f4e85f4ad4f91b583ddef249e5d47e.webm](https://user-images.githubusercontent.com/12484408/210066796-45d4a939-23b0-4af6-ba9c-af7091e128dc.webm)

**Resultado esperado**
Se debería de visualizar el número de orden generado, por ejemplo:
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/12484408/210027225-9f422573-387c-46f6-9339-f0a18a8a252c.png">

**Comment by mauromm** [comment]
Next Exception: An exception occurred on 'sales_model_service_quote_submit_failure' event: Could not ping search engine: No alive nodes found in your cluster in /var/www/rebillnuevo/v
endor/magento/module-quote/Model/QuoteManagement.php:743
Stack trace:
#0 /var/www/rebillnuevo/vendor/magento/module-quote/Model/QuoteManagement.php(614): Magento\Quote\Model\QuoteManagement->rollbackAddresses()
#1 /var/www/rebillnuevo/vendor/magento/module-quote/Model/QuoteManagement.php(483): Magento\Quote\Model\QuoteManagement->submitQuote()
#2 /var/www/rebillnuevo/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteManagement->submit()
#3 /var/www/rebillnuevo/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteManagement\Interceptor->___callParent()
#4 /var/www/rebillnuevo/vendor/magento/module-sales-rule/Plugin/CouponUsagesIncrement.php(54): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure
}()
#5 /var/www/rebillnuevo/vendor/magento/framework/Interception/Interceptor.php(135): Magento\SalesRule\Plugin\CouponUsagesIncrement->aroundSubmit()
#6 /var/www/rebillnuevo/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}()
#7 /var/www/rebillnuevo/generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(32): Magento\Quote\Model\QuoteManagement\Interceptor->___callPlugins()
#8 /var/www/rebillnuevo/vendor/magento/module-quote/Model/QuoteManagement.php(441): Magento\Quote\Model\QuoteManagement\Interceptor->submit()
#9 /var/www/rebillnuevo/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteManagement->placeOrder()
#10 /var/www/rebillnuevo/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteManagement\Interceptor->___callParent()
#11 /var/www/rebillnuevo/vendor/paypal/module-braintree-core/Plugin/OrderCancellation.php(63): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure
}()
#12 /var/www/rebillnuevo/vendor/magento/framework/Interception/Interceptor.php(135): PayPal\Braintree\Plugin\OrderCancellation->aroundPlaceOrder()
#13 /var/www/rebillnuevo/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}()
#14 /var/www/rebillnuevo/generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(23): Magento\Quote\Model\QuoteManagement\Interceptor->___callPlugins()
#15 /var/www/rebillnuevo/vendor/magento/module-checkout/Model/PaymentInformationManagement.php(125): Magento\Quote\Model\QuoteManagement\Interceptor->placeOrder()
#16 /var/www/rebillnuevo/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Model\PaymentInformationManagement->savePaymentInformationAndPlaceOrder()
#17 /var/www/rebillnuevo/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callParent()
#18 /var/www/rebillnuevo/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->Magento\Framework\Interception\{c
losure}()
#19 /var/www/rebillnuevo/generated/code/Magento/Checkout/Model/PaymentInformationManagement/Interceptor.php(23): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___ca
llPlugins()
#20 [internal function]: Magento\Checkout\Model\PaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder()
#21 /var/www/rebillnuevo/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array()
#22 /var/www/rebillnuevo/vendor/magento/module-webapi/Controller/Rest.php(195): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process()
#23 /var/www/rebillnuevo/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch()
#24 /var/www/rebillnuevo/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent()
#25 /var/www/rebillnuevo/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
#26 /var/www/rebillnuevo/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins()
#27 /var/www/rebillnuevo/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch()
#28 /var/www/rebillnuevo/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#29 /var/www/rebillnuevo/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#30 /var/www/rebillnuevo/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#31 {main} [] []
[2022-12-29T22:02:14.191083+00:00] main.CRITICAL: PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/rebillnuevo/vendor/magento/zendframework1/library/Zend/Db/Adapter
/Pdo/Abstract.php:128
Stack trace:
#0 /var/www/rebillnuevo/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(128): PDO->__construct()
#1 /var/www/rebillnuevo/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Mysql.php(111): Zend_Db_Adapter_Pdo_Abstract->_connect()
#2 /var/www/rebillnuevo/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(428): Zend_Db_Adapter_Pdo_Mysql->_connect()
#3 /var/www/rebillnuevo/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(593): Magento\Framework\DB\Adapter\Pdo\Mysql->_connect()
#4 /var/www/rebillnuevo/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(634): Magento\Framework\DB\Adapter\Pdo\Mysql->_query()
#5 /var/www/rebillnuevo/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(756): Magento\Framework\DB\Adapter\Pdo\Mysql->query()
#6 /var/www/rebillnuevo/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(333): Zend_Db_Adapter_Abstract->fetchRow()
#7 /var/www/rebillnuevo/vendor/magento/framework/Model/AbstractModel.php(543): Magento\Framework\Model\ResourceModel\Db\AbstractDb->load()
#8 /var/www/rebillnuevo/vendor/magento/module-sales-rule/Model/Coupon.php(74): Magento\Framework\Model\AbstractModel->load()
#9 /var/www/rebillnuevo/vendor/magento/module-sales-rule/Plugin/CartTotalRepository.php(78): Magento\SalesRule\Model\Coupon->loadByCode()
#10 /var/www/rebillnuevo/vendor/magento/framework/Interception/Interceptor.php(146): Magento\SalesRule\Plugin\CartTotalRepository->afterGet()
#11 /var/www/rebillnuevo/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\Cart\CartTotalRepository\Interceptor->Magento\Framework\Interception\{closure}
()
