### ISSUE TITLE
** CRITICAL ** Mail Notification | Subscription Reorder Failed

### ISSUE THREAD

**Issue by gustavorebill** [improntus/module-rebill#61]
Se recibe el mail siguiente mail de forma constante

Resultado Actual:
[
    "El producto [REB][AUT] Subs only - With base price no es vendible",
    "No items available found.",
    "Pedido #000002018",
    "Suscripciones: 4083b11a-24ad-4b79-bf7b-7e06c2c30f1f"
]

[Rebill, Inc. Mail - Subscription Reorder Failed.pdf](https://github.com/improntus/module-rebill/files/10326650/Rebill.Inc.Mail.-.Subscription.Reorder.Failed.pdf)

**Comment by brunojbarros** [comment]
Dejo algunos emails más que llegaron con este motivo:
[Correo de Rebill, Inc. - Subscription Reorder Failed 2022-12-31.pdf](https://github.com/improntus/module-rebill/files/10331721/Correo.de.Rebill.Inc.-.Subscription.Reorder.Failed.2022-12-31.pdf)
[Correo de Rebill, Inc. - Subscription Reorder Failed - 2023-01-01.pdf](https://github.com/improntus/module-rebill/files/10331722/Correo.de.Rebill.Inc.-.Subscription.Reorder.Failed.-.2023-01-01.pdf)

**Comment by mauromm** [comment]
Gustavo, esto es porque hay una suscripción que esta llegando desde rebill y el producto que se utiliza no es vendible, lo que quiere decir que no tiene stock, no esta habilitado o no existe. Va a pasar esto cada vez que se envíe el webhook y magento no pueda crear el pedido. No es un error.

**Comment by brunojbarros** [comment]
@mauromm 
no se cumple ninguna de las condiciones que indicás, el producto existe, tiene stock y está habilitado, podés validarlo ingresando al detalle del producto:
https://rebillnuevo.improntus.dev/admin/catalog/product/index/key/b278f695a9a9d144b3c25883c0121ef20fad266374028fd508e54f597c997657/

Lo mismo sucede con los demás productos con los que llegaron un email.

**Comment by gustavorebill** [comment]
Agrego nuevos escenarios.
[Rebill, Inc. Mail - Subscription Reorder Failed 2.pdf .pdf](https://github.com/improntus/module-rebill/files/10337390/Rebill.Inc.Mail.-.Subscription.Reorder.Failed.2.pdf.pdf)

**Comment by mauromm** [comment]
Este ya lo dejamos resuelto. Les volvio a pasar? asi lo cerramos

**Comment by brunojbarros** [comment]
@mauromm 
No volví a recibir el email de que no se pudo crear el pedido, pero, por ejemplo, se loguea en la queue que no se pude crear el pedido:

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/12484408/211054035-3eaad654-54cc-4079-9bd7-13b62a271e96.png">

**Comment by brunojbarros** [comment]
@mauromm @MauroImp91 
Por lo que veo, el problema fue el headsup del shipping.

**Comment by brunojbarros** [comment]
@mauromm @MauroImp91 
realizando otra prueba sobre la misma suscripción, ahora hubo inconvenientes tanto en la suscripción del producto como el del shipping:

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/12484408/211076271-810766dc-8593-48df-8cd1-bacbf67d57ba.png">

**Comment by MauroImp91** [comment]
@brunojbarros 

Estuvimos revisando esos casos por lo que pudimos ver habían suscripciones que no estaban activas, luego se enviaron los webhooks de una suscripcion seguido de otro webhook del shipment. Este ultimo falla porque ya se encuentra actualizado por el webhook de la subscription.
Por otro lado vi algunos webhook que realizaban el cambio de precio, les comento que hay una validación para el campo nextChargeDate, esta validación verifica si es el mismo valor del que ya se proceso anteriormente. Al ser el mismo, no lo va a volver a procesar, lo toma como que ya se encuentra actualizado.

**Comment by brunojbarros** [comment]
@MauroImp91 
¿Cuáles son las suscripciones que notaron que no estaban activas? En el caso de las que no, ¿cuál fue en motivo?

Siempre que se va a enviar un webhook de headsup por cada suscripción, en este caso, uno por la suscripción del producto y una por la suscripción del shipping, de cara a Rebill son dos suscripciones distintas, no discriminamos si hacen referencia a un producto o shipping.

En algunos casos, falló la generación de la orden tanto al recibir el headsup por el producto como en el shipping (es lo que comentaba acá https://github.com/improntus/module-rebill/issues/61#issuecomment-1373990693), ¿estos casos por qué se dio?


No me queda claro cómo se va a avanzar para solucionar este inconveniente en cada uno de los escenarios.

**Comment by MauroImp91** [comment]
@brunojbarros 

1)Sobre la suscripcion que notamos que estaba cancelada, supuse que la cancelaron desde su lado por alguna prueba no conozco realmente el motivo.
2) Ok, pero en ese caso no habría problema ya que tanto la suscripcion como el shipment se actualizaron de forma correcta.
3) Esos casos se dio por lo que comente antes, por lo que vi desde su lado estaban realizando pruebas de cambiar de precio tanto en el producto como en la frecuencia. Hay una validación para el campo nextChargeDate, esta validación verifica si es el mismo valor del que ya se proceso anteriormente, al ser el mismo no procesa este nuevo headsUp

**Comment by brunojbarros** [comment]
@MauroImp91 
1) ¿Podrás indicarme los IDs de las que detectaste canceladas?
2) Te comento por las dudas, de que hay varios bugs relacionados a que no se realiza la actualización correctamente (ver #74 #75 #76 )
3) Entiendo, pero tampoco deberían quedar en queue como si algo hubiera fallado, porque:
- da la sensación de que algo funciona mal
- entre tantos logs, se van a perder errores reales
- se da la posibilidad de hacer un "Retry" cuando en realidad va a volver a fallar

**Comment by MauroImp91** [comment]
@brunojbarros 
Ya hicimos la modificación para que cuando se quiera realizar un HeadsUp que no este activo o que el campo "nextChargeDate" sea igual al que se proceso anteriormente no figure como un error.
Por otro lado, el HeadsUp que fallo al tener la subscription cancelada es la del id "ab693a36-84a4-4e6e-a528-49b08a1af902".

**Comment by brunojbarros** [comment]
@MauroImp91 

Acabo de revisar la suscripción cancelada, y efectivamente es una vieja (creada el 2022-12-07), por lo cual es probable que se haya cancelado adrede en su momento.

Se verificó que:

- no se loguee un error cuando se reciben más de un headsup por el mismo "paquete" de suscripciones.
- no se genere un error cuando la suscripción no está activo.
