### ISSUE TITLE
Magento | Rebill | Subscription | La fecha de Last Charge Date es invalida

### ISSUE THREAD

**Issue by gustavorebill** [improntus/module-rebill#63]
Descripción:
Se puede observar que la fecha de last charge date es invalida se muestra Today - 1 .

Steps:
Ingresar a Magento
Ingresar a Rebill
Ingresar a suscripciones 
Observar

Resultado Actual:

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/109085275/210120788-ae96b847-5401-4e54-91c1-765cd9ac96ee.png">

**Comment by MauroImp91** [comment]
Sobre estas fechas en Rebill que huso horario se están utilizando? Así la dejo configurada de la misma forma que su plataforma.
La columna que mencionan la tenemos configurada con GMT-3

**Comment by brunojbarros** [comment]
@MauroImp91 
guardamos en UTC en nuestra BDD, y luego en el dashboard de Rebill renderizamos acorde al timezone del usuario. Igualmente, dada la conversión de UTC a GMT-3, se muestra de manera incorrecta.

**Comment by MauroImp91** [comment]
@brunojbarros 
Listo Bruno, ahí subimos un cambio para solucionar esto.
Avísanos cualquier novedad!

**Comment by brunojbarros** [comment]
@MauroImp91 @mauromm 
Quedó resuelto el bug, por lo lo cierro.

Por favor, tengan en cuenta avanzar con aquellos que son más prioritarios: [P1](https://github.com/improntus/module-rebill/issues?q=is%3Aissue+is%3Aopen+label%3AP1), luego [P2](https://github.com/improntus/module-rebill/issues?q=is%3Aissue+is%3Aopen+label%3AP2) y por último [P3](https://github.com/improntus/module-rebill/issues?q=is%3Aissue+is%3Aopen+label%3AP3).
