### ISSUE TITLE
[Checkout] Al editar un producto del carrito, no se precarga correctamente el producto seleccionado

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#7]
**Funcionalidad/módulo**
Checkout / Edición de carrito

**Comportamiento actual**
Cuando se edita un producto del carrito, no se precarga correctamente el mismo, sino que siempre se precarga como "Compra única" por más que previamente se haya elegido suscribirse al mismo.

https://user-images.githubusercontent.com/12484408/201694609-a77fe30b-4e4d-467e-9576-1066638d984a.mov

**Resultado esperado**
Se espera que se precargue con los valores seleccionados previamente.

**Comment by mauromm** [comment]
Hola Bruno, este comportamiento es correcto, no es un bug. Luego de añadir un producto al carrito, el formulario se resetea y no queda en ninguna posición por defecto.

**Comment by brunojbarros** [comment]
@mauromm tengamos en cuenta que esto puede inducir a errores de parte del customer ya que debe estar atento a todos los valores.
