### ISSUE TITLE
[Customer portal] Se permite cambiar la tarjeta de una suscripción que no está activa

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#8]
**Funcionalidad/módulo**
Customer portal / Suscripciones

**Comportamiento actual**
Se visualiza el botón "Actualizar" para cambiar la tarjeta por más que la suscripción no esté activa, esto causa que luego se obtenga un 400 al confirmar el cambio de tarjeta.

<img width="1435" alt="Captura de Pantalla 2022-11-14 a la(s) 15 19 08" src="https://user-images.githubusercontent.com/12484408/201736265-037ba80b-4461-4fc1-90b7-f26013fd1ffa.png">

<img width="914" alt="Captura de Pantalla 2022-11-14 a la(s) 15 13 30" src="https://user-images.githubusercontent.com/12484408/201736090-3384b615-8807-4ca5-88ec-f9d29bc0b7bf.png">

**Resultado esperado**
Se espera que no se visualice el botón "Actualizar"

**Comment by mauromm** [comment]
Bruno, ¿como hiciste para que una suscripción no este activa pero se quede como que sí lo está en el panel del usuario?

**Comment by brunojbarros** [comment]
@mauromm no realicé ningún flujo en particular, simplemente la pausé desde el panel de usuario:

https://user-images.githubusercontent.com/12484408/202019559-d9f50738-ea1c-4eca-a0cc-cb1857f8b1c6.mov

**Comment by brunojbarros** [comment]
@mauromm la condición debería ser si no está activa en vez de si está pausada, ya que el único estado válido para usar `PUT clients/subscriptions/{id}` es activo

También habría que agregar la validación al ingresar a la pantalla para actualizar la tarjeta: podría darse el caso border, de que el customer ya esté por cambiar la tarjeta, y el merchant le cambie el estado, por ejemplo, a cancelado.

**Comment by mauromm** [comment]
Agregamos la validación para que no deje hacerlo sobre pausadas. La otra validación la dejamos como una mejora posterior.

**Comment by brunojbarros** [comment]
@mauromm entiendo que la complejidad de las validaciones es la misma, ¿se podrá agregar la validación con status === active?
