### ISSUE TITLE
[Checkout] El precio se genera sin configuración (price setting)

### ISSUE THREAD

**Issue by brunojbarros** [improntus/module-rebill#9]
**Funcionalidad/módulo**
Checkout / Creación de precios de la orden

**Comportamiento actual**
Cuando se genera el precio al momento de confirmar la orden, no se genera price setting (https://docs.rebill.to/reference/itemcontroller_createpricesetting); esto en un futuro hará que fallen los checkouts.

**Resultado esperado**
Se debería crear un price setting, dado que en un futuro se agregará una validación que compruebe si el precio está configurado.

**Comment by mauromm** [comment]
Ya esta listo este agregado.
